import Center from "@/components/Home/Center/Center";
import Left from "@/components/Home/Left/Left";
import Right from "@/components/Home/Right/Right";
import PageLayout from "@/components/Layout/PageLayout";
import { auth } from "@/firebase/clientApp";
import { Box, Flex, Text } from "@chakra-ui/react";
import Head from "next/head";
import { useAuthState } from "react-firebase-hooks/auth";

export default function Home() {
  const [user] = useAuthState(auth);
  return (
    <>
      <Head>
        <title>Aara Co Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/logo.jpg" />
      </Head>
      {user ? (
        <Box>
          <PageLayout>
            <>
              <Left />
            </>
            <>
              <Center />
            </>
            <>
              <Right />
            </>
          </PageLayout>
        </Box>
      ) : (
        <Flex mt={10} width="100%" align="center" justify="center">
          <Text fontWeight={900} fontSize="15pt">
            Sign in to Access Admin
          </Text>
        </Flex>
      )}
    </>
  );
}
